const units = {
  1:{title:"Personal Interests",ar:"الاهتمامات الشخصية"},
  2:{title:"House Designs",ar:"تصاميم المنازل"},
  3:{title:"Job Paths",ar:"المهن المستقبلية"},
  4:{title:"Glorious Food",ar:"الطعام الصحي"},
  5:{title:"Storylines",ar:"القصص والأفلام"},
  6:{title:"Outdoor Activities",ar:"الأنشطة الخارجية"},
  7:{title:"Trips",ar:"السفر والرحلات"},
  8:{title:"Outfits",ar:"الملابس والخامات"}
};

const skillMeta = {
  general:{ar:"أسئلة عامة",topic:"فهم السؤال والإجابة بجملة مناسبة"},
  reading:{ar:"القراءة",topic:"استخراج الفكرة والتفاصيل من النص"},
  grammar:{ar:"القواعد",topic:"اختيار الزمن والتركيب الصحيح"},
  vocabulary:{ar:"المفردات",topic:"معاني كلمات الوحدات واستخدامها"},
  writing:{ar:"الكتابة",topic:"ترتيب الكلمات وبناء الجملة"},
  spelling:{ar:"الإملاء",topic:"تهجئة الكلمات وأجزاء الكلمة"},
  listening:{ar:"الاستماع",topic:"التقاط التفاصيل من المقطع الصوتي"}
};

const questions = [
  {id:"u1-g1",unit:1,skill:"grammar",prompt:"Maha usually ___ origami after school, but yesterday she painted.",choices:["makes","made","is making","make"],answer:0,explanation:"وجود usually يدل على عادة، لذلك نستخدم المضارع البسيط مع Maha: makes.",detail:"مع he / she / it نضيف غالبًا s للفعل في المضارع البسيط."},
  {id:"u1-g2",unit:1,skill:"grammar",prompt:"Look! My cousins ___ on the new ride right now.",choices:["go","went","are going","goes"],answer:2,explanation:"right now و Look تدلان على حدث يجري الآن، فنستخدم are going.",detail:"المضارع المستمر يتكون من am/is/are + verb-ing."},
  {id:"u1-v1",unit:1,skill:"vocabulary",prompt:"Which word means “very big”?",choices:["tidy","enormous","friendly","lucky"],answer:1,explanation:"Enormous تعني ضخم جدًا أو very big.",detail:"مثال: The new library is enormous."},
  {id:"u1-v2",unit:1,skill:"vocabulary",prompt:"The opposite of “friendly” is ___.",choices:["unfriendly","unlucky","untidy","unusual"],answer:0,explanation:"نضيف السابقة un- إلى friendly لتصبح unfriendly.",detail:"السابقة un- تعكس المعنى: kind / unkind و tidy / untidy."},
  {id:"u1-w1",unit:1,skill:"writing",prompt:"Choose the correctly ordered sentence.",choices:["I enjoy reading comic books.","Enjoy I comic books reading.","Comic books I reading enjoy.","Reading enjoy I books comic."],answer:0,explanation:"الترتيب الصحيح: فاعل ثم فعل ثم بقية الجملة.",detail:"بعد enjoy نستخدم verb + ing: enjoy reading."},
  {id:"u1-s1",unit:1,skill:"spelling",prompt:"Choose the correctly spelled adjective.",choices:["intresting","interesting","interisting","enteresting"],answer:1,explanation:"التهجئة الصحيحة هي interesting.",detail:"قسّمها عند الحفظ: inter + est + ing."},

  {id:"u2-g1",unit:2,skill:"grammar",prompt:"We ___ redesign the bedroom next weekend. This is our plan.",choices:["are going to","were","has","did"],answer:0,explanation:"لأنها خطة مقررة نستخدم be going to.",detail:"going to يناسب الخطط الموجودة مسبقًا."},
  {id:"u2-g2",unit:2,skill:"grammar",prompt:"The phone is ringing. I ___ answer it.",choices:["am going","will","was","have"],answer:1,explanation:"هذا قرار اتخذ في اللحظة نفسها، لذلك will هو الأنسب.",detail:"الصيغة: will + base verb، لذلك will answer."},
  {id:"u2-v1",unit:2,skill:"vocabulary",prompt:"Where do you usually keep food cold?",choices:["In a fridge","On a shelf","At the gate","In the entrance"],answer:0,explanation:"نحفظ الطعام باردًا في fridge أي الثلاجة.",detail:"Oven للتسخين، وfridge للتبريد."},
  {id:"u2-v2",unit:2,skill:"vocabulary",prompt:"An architect needs the room’s ___ before making a plan.",choices:["measurements","cushions","screens","keys"],answer:0,explanation:"يحتاج المهندس إلى measurements أي قياسات الغرفة.",detail:"Measurement اسم بمعنى قياس، وجمعها measurements."},
  {id:"u2-w1",unit:2,skill:"writing",prompt:"Choose the best sentence about a future plan.",choices:["I am going to add a new shelf.","I going add a shelf.","I am add a new shelf.","I to going add shelf."],answer:0,explanation:"الصيغة الصحيحة: subject + be + going to + base verb.",detail:"مع I نستخدم am: I am going to add."},
  {id:"u2-r1",unit:2,skill:"reading",passage:"Mariam’s future house will use sunlight for energy. It will have a small garden on the roof and large windows, but it will not have a basement.",prompt:"Which feature will NOT be in the house?",choices:["A basement","Large windows","A roof garden","Solar energy"],answer:0,explanation:"النص يقول بوضوح it will not have a basement.",detail:"انتبه إلى كلمة NOT في السؤال وإلى النفي في النص."},

  {id:"u3-g1",unit:3,skill:"grammar",prompt:"Salma loves airplanes. She ___ become a pilot one day.",choices:["might","was","has","did"],answer:0,explanation:"might تعبّر عن احتمال مستقبلي غير مؤكد.",detail:"بعد may و might نستخدم الفعل في صورته الأساسية."},
  {id:"u3-g2",unit:3,skill:"grammar",prompt:"This is the new theater, ___?",choices:["is it","isn’t it","doesn’t it","was it"],answer:1,explanation:"الجملة مثبتة وبها is، لذا السؤال المذيل منفي: isn’t it?",detail:"الجملة المثبتة تتبعها أداة منفية في question tags."},
  {id:"u3-v1",unit:3,skill:"vocabulary",prompt:"Who repairs cars and machines?",choices:["A journalist","A mechanic","A pilot","A waiter"],answer:1,explanation:"A mechanic هو الميكانيكي الذي يصلح السيارات والآلات.",detail:"Journalist يكتب الأخبار، وpilot يقود الطائرة."},
  {id:"u3-v2",unit:3,skill:"vocabulary",prompt:"A person who takes professional photos is a ___.",choices:["photographer","manager","engineer","driver"],answer:0,explanation:"Photographer تعني مصورًا فوتوغرافيًا.",detail:"اللاحقة -er قد تدل على صاحب المهنة."},
  {id:"u3-a1",unit:3,skill:"general",prompt:"Where does a flight attendant usually work?",choices:["On an airplane","In a gallery","In a factory","On a stage"],answer:0,explanation:"يعمل مضيف الطيران على متن الطائرة.",detail:"إجابة كاملة: A flight attendant works on an airplane."},

  {id:"u4-g1",unit:4,skill:"grammar",prompt:"You ___ drink enough water every day.",choices:["should","might not","were","has"],answer:0,explanation:"نستخدم should لتقديم نصيحة إيجابية.",detail:"للنصيحة المنفية نقول shouldn’t."},
  {id:"u4-g2",unit:4,skill:"grammar",prompt:"If the soup is too thick, we ___ a little water.",choices:["add","added","will adding","are add"],answer:0,explanation:"هذه تعليمات متكررة، لذا نستخدم zero conditional بالمضارع.",detail:"If + present simple, present simple."},
  {id:"u4-v1",unit:4,skill:"vocabulary",prompt:"Which ingredient is made from milk?",choices:["Yogurt","Flour","Sugar","Honey"],answer:0,explanation:"Yogurt من منتجات الحليب.",detail:"Dairy products تشمل milk, yogurt, and cheese."},
  {id:"u4-v2",unit:4,skill:"vocabulary",prompt:"To move food around with a spoon means to ___.",choices:["stir","roll","bake","fetch"],answer:0,explanation:"Stir تعني يحرّك الطعام بملعقة.",detail:"Mix خلط عام، وstir تحريك غالبًا بحركة دائرية."},
  {id:"u4-r1",unit:4,skill:"reading",passage:"Omar wanted a healthy snack. He cut an apple, added yogurt, and put a little honey on top. He did not use any sugar.",prompt:"What did Omar put on top of the snack?",choices:["A little honey","Some flour","A lot of sugar","Butter"],answer:0,explanation:"ذكر النص أنه وضع a little honey on top.",detail:"ابحث عن الكلمات المفتاحية في السؤال ثم طابقها مع النص."},
  {id:"u4-w1",unit:4,skill:"writing",prompt:"Choose the correct warning.",choices:["You had better not touch the hot oven.","You better not touching hot oven.","You had not better touch oven.","You had better not touched it."],answer:0,explanation:"التركيب الصحيح: had better not + base verb.",detail:"لا نستخدم to ولا نغير الفعل بعد had better."},
  {id:"u4-a1",unit:4,skill:"general",prompt:"What should you do when you feel sick?",choices:["I should visit a doctor.","It is made of wood.","I was watching a movie.","It is on the platform."],answer:0,explanation:"الإجابة المناسبة هي زيارة الطبيب.",detail:"طابق معنى السؤال مع الإجابة أولًا."},

  {id:"u5-g1",unit:5,skill:"grammar",prompt:"At 8 p.m. yesterday, I ___ a mystery movie.",choices:["was watching","watch","am watching","have watched"],answer:0,explanation:"الحدث كان مستمرًا في وقت محدد بالماضي: was watching.",detail:"Past progressive: was/were + verb-ing."},
  {id:"u5-g2",unit:5,skill:"grammar",prompt:"___ you studying when your friend called?",choices:["Were","Was","Did","Are"],answer:0,explanation:"مع you في الماضي المستمر نبدأ السؤال بـ Were.",detail:"Were + subject + verb-ing."},
  {id:"u5-g3",unit:5,skill:"grammar",prompt:"Choose the correct suggestion.",choices:["How about making a storyboard?","How about make a storyboard?","Why don’t making a storyboard?","What about to make a storyboard?"],answer:0,explanation:"بعد How about نستخدم verb + ing.",detail:"Why don’t we + base verb، لكن How about + verb-ing."},
  {id:"u5-v1",unit:5,skill:"vocabulary",prompt:"A story that makes people laugh is a ___.",choices:["comedy","horror","documentary","thriller"],answer:0,explanation:"Comedy نوع من القصص هدفه الإضحاك.",detail:"Horror مخيف، وdocumentary وثائقي."},
  {id:"u5-v2",unit:5,skill:"vocabulary",prompt:"The people in a story are called ___.",choices:["characters","acts","plots","storyboards"],answer:0,explanation:"Characters هم الشخصيات التي تظهر في القصة.",detail:"Plot هو تسلسل الأحداث، وstoryboard مخطط المشاهد."},
  {id:"u5-r1",unit:5,skill:"reading",passage:"Noura was preparing a school play. While she was drawing the storyboard, Sami was writing the ending. They chose a comedy because they wanted the audience to laugh.",prompt:"Why did they choose a comedy?",choices:["They wanted the audience to laugh.","They wanted to teach cooking.","They did not have a storyboard.","They were watching a western."],answer:0,explanation:"الجملة الأخيرة تذكر السبب بوضوح.",detail:"كلمة Why تسأل عن السبب؛ ابحث عن because."},
  {id:"u5-r2",unit:5,skill:"reading",passage:"In Act I, Lina found an old map. In Act II, she crossed a desert. In Act III, she found the hidden library and returned home safely.",prompt:"What happened in Act II?",choices:["Lina crossed a desert.","Lina found the map.","Lina returned home.","Lina wrote a comedy."],answer:0,explanation:"في الفصل الثاني عبرت لينا الصحراء.",detail:"القصة عادة من ثلاثة فصول: بداية، تصاعد، ثم حل."},
  {id:"u5-l1",unit:5,skill:"listening",audio:"assets/audio/storylines-5-7.mp3",prompt:"Listen to the story. Which kind of story is Liliana telling?",choices:["A fairy tale","A comedy","A documentary","A western"],answer:0,explanation:"المقطع يقدم حكاية خيالية، لذلك هي fairy tale.",detail:"استمع للأحداث الخيالية والشخصيات، ولا تعتمد على كلمة واحدة."},
  {id:"u5-w1",unit:5,skill:"writing",prompt:"Choose the correctly ordered suggestion.",choices:["Why don’t we write a mystery?","Why we don’t a mystery write?","Why don’t writing we a mystery?","We why write don’t mystery?"],answer:0,explanation:"الصيغة: Why don’t + subject + base verb.",detail:"لا نضيف ing إلى write في هذا التركيب."},
  {id:"u5-s1",unit:5,skill:"spelling",prompt:"Complete the word: docu___tary",choices:["men","man","min","mon"],answer:0,explanation:"الكلمة الصحيحة documentary، والجزء الناقص men.",detail:"قسّمها: docu + men + tary."},

  {id:"u6-g1",unit:6,skill:"grammar",prompt:"We were hiking when it ___ to rain.",choices:["started","was starting","starts","has started"],answer:0,explanation:"قطع الحدث المستمر حدث قصير بالماضي البسيط: started.",detail:"when تربط غالبًا حدثًا مستمرًا بحدث قصير."},
  {id:"u6-g2",unit:6,skill:"grammar",prompt:"While Dad was putting up the tent, we ___ the backpacks.",choices:["were carrying","carried now","have carry","are carried"],answer:0,explanation:"حدثان كانا يجريان معًا، لذلك نستخدم الماضي المستمر.",detail:"While كثيرًا ما تربط حدثين مستمرين."},
  {id:"u6-v1",unit:6,skill:"vocabulary",prompt:"What protects your head while climbing?",choices:["A helmet","A sleeping bag","A fishing rod","A raft"],answer:0,explanation:"Helmet هي الخوذة التي تحمي الرأس.",detail:"Life jacket للحماية في الماء."},
  {id:"u6-v2",unit:6,skill:"vocabulary",prompt:"Which item do you sleep in during a camping trip?",choices:["A sleeping bag","A surfboard","A canoe","A flashlight"],answer:0,explanation:"Sleeping bag هي حقيبة النوم.",detail:"Tent هي الخيمة، وداخلها sleeping bag."},
  {id:"u6-r1",unit:6,skill:"reading",passage:"Faisal packed a flashlight, a life jacket, and water. He was going rafting with his family. He left his hiking boots at home.",prompt:"Which activity was Faisal going to do?",choices:["Rafting","Hiking","Climbing","Fishing"],answer:0,explanation:"ذكر النص مباشرة أنه was going rafting.",detail:"life jacket وraft دليلان إضافيان."},
  {id:"u6-a1",unit:6,skill:"general",prompt:"Where can you go hiking?",choices:["In the mountains","In an oven","On a stage","In a fridge"],answer:0,explanation:"Hiking يمارس عادة في الجبال.",detail:"إجابة كاملة: I can go hiking in the mountains."},
  {id:"u6-s1",unit:6,skill:"spelling",prompt:"Unscramble: m / h / e / l / e / t",choices:["helmet","methel","heltem","melthe"],answer:0,explanation:"ترتيب الحروف الصحيح يعطي helmet.",detail:"اربط التهجئة بالنشاط: climbing helmet."},

  {id:"u7-g1",unit:7,skill:"grammar",prompt:"Sara ___ on the subway before.",choices:["has traveled","traveled tomorrow","is travel","have traveled"],answer:0,explanation:"نتحدث عن تجربة حتى الآن: has traveled.",detail:"Present perfect: has/have + past participle."},
  {id:"u7-g2",unit:7,skill:"grammar",prompt:"The taxi has ___ arrived. It is outside now.",choices:["just","yet","ago","last"],answer:0,explanation:"just تعني للتو وتناسب الحدث الذي وقع منذ لحظات.",detail:"yet غالبًا في السؤال أو النفي."},
  {id:"u7-g3",unit:7,skill:"grammar",prompt:"We haven’t checked in at the hotel ___.",choices:["yet","just","last week","ago"],answer:0,explanation:"yet تأتي عادة في نهاية الجملة المنفية.",detail:"We haven’t checked in yet."},
  {id:"u7-v1",unit:7,skill:"vocabulary",prompt:"Where do passengers wait for a train?",choices:["On a platform","At a gallery","In a factory","On a countertop"],answer:0,explanation:"ينتظر الركاب القطار على platform.",detail:"Station هي المحطة، وplatform هو الرصيف."},
  {id:"u7-v2",unit:7,skill:"vocabulary",prompt:"Before an international trip, you must take your ___.",choices:["passport","cushion","fishing rod","recipe"],answer:0,explanation:"Passport هو جواز السفر.",detail:"في المطار تمر عبر security ثم تتجه إلى gate."},
  {id:"u7-w1",unit:7,skill:"writing",prompt:"Choose the correct present perfect sentence.",choices:["Mom has already printed the tickets.","Mom already has print the tickets.","Mom have printed already tickets.","Mom has printing the tickets."],answer:0,explanation:"التركيب الصحيح: has + past participle.",detail:"print فعل منتظم، والتصريف الثالث printed."},
  {id:"u7-r1",unit:7,skill:"reading",passage:"The family reached the station early. Their train had not arrived yet, so they checked the platform number. Ten minutes later, it arrived.",prompt:"Why did the family wait?",choices:["The train had not arrived yet.","They lost their passports.","They were buying clothes.","The station was closed."],answer:0,explanation:"انتظروا لأن القطار لم يصل بعد.",detail:"السؤال Why يطلب السبب."},

  {id:"u8-g1",unit:8,skill:"grammar",prompt:"___ you tried the new school uniform?",choices:["Have","Has","Did have","Are"],answer:0,explanation:"مع you نستخدم Have في سؤال المضارع التام.",detail:"Have + subject + past participle."},
  {id:"u8-g2",unit:8,skill:"grammar",prompt:"This bracelet is made ___ silver.",choices:["of","from to","with of","at"],answer:0,explanation:"نستخدم be made of لذكر المادة.",detail:"The ring is made of gold."},
  {id:"u8-v1",unit:8,skill:"vocabulary",prompt:"Which material comes from sheep?",choices:["Wool","Metal","Plastic","Silk"],answer:0,explanation:"Wool هو الصوف ويأتي من الأغنام.",detail:"Cotton نباتي، وmetal معدن."},
  {id:"u8-v2",unit:8,skill:"vocabulary",prompt:"Which accessory is worn around the neck?",choices:["A necklace","A belt","A ring","A bracelet"],answer:0,explanation:"Necklace هي القلادة التي تلبس حول الرقبة.",detail:"Bracelet حول المعصم، وring في الإصبع."},
  {id:"u8-r1",unit:8,skill:"reading",passage:"Hind wore a striped cotton shirt, a leather belt, and a silver necklace. She did not wear earrings.",prompt:"What was the shirt made of?",choices:["Cotton","Leather","Silver","Gold"],answer:0,explanation:"النص يصفها بأنها striped cotton shirt.",detail:"ركّز على كلمات الخامات في السؤال والنص."},
  {id:"u8-s1",unit:8,skill:"spelling",prompt:"Choose the correctly spelled travel item.",choices:["suitcase","sutcase","suitcace","suitecase"],answer:0,explanation:"التهجئة الصحيحة هي suitcase.",detail:"هي كلمة مركبة من suit + case."},

  // اختبار مستقل صعب: معاني مفردات الكتاب وتكوين الجمل.
  {id:"wm-v01",exam:"word-mastery",unit:1,skill:"vocabulary",prompt:"Rose’s hobby is unusual; very few people in her town do it. What does “unusual” mean?",choices:["Not common","Very noisy","Easy to learn","Done every day"],answer:0,explanation:"Unusual تعني غير معتاد أو غير شائع.",detail:"وجود very few people يؤكد أن الهواية ليست common. السابقة un- تعكس معنى usual."},
  {id:"wm-v02",exam:"word-mastery",unit:1,skill:"vocabulary",prompt:"After the festival, the room was untidy. Which sentence has the closest meaning?",choices:["The room was not neat.","The room was completely empty.","The room was very frightening.","The room was quiet and clean."],answer:0,explanation:"Untidy تعني غير مرتب، وأقرب معنى هو not neat.",detail:"Tidy = neat and organized، وإضافة un- تجعل المعنى عكسه."},
  {id:"wm-v03",exam:"word-mastery",unit:2,skill:"vocabulary",prompt:"The architect checked the measurements before changing the layout. What are “measurements”?",choices:["The exact sizes of something","The materials used to build","Pictures of the entrance","Keys for every room"],answer:0,explanation:"Measurements هي القياسات الدقيقة مثل الطول والعرض والارتفاع.",detail:"لا تعني layout؛ فالـ layout هو ترتيب المساحات، أما measurements فهي الأبعاد."},
  {id:"wm-v04",exam:"word-mastery",unit:2,skill:"vocabulary",prompt:"There is no furniture in the basement, so it is ___.",choices:["empty","enormous","actually","special"],answer:0,explanation:"Empty تعني فارغًا، وهي الأنسب لأن المكان بلا أثاث.",detail:"السياق هو المفتاح: no furniture = empty."},
  {id:"wm-v05",exam:"word-mastery",unit:3,skill:"vocabulary",prompt:"Which job is correctly matched with its workplace?",choices:["A flight attendant — an airplane","A mechanic — a gallery","A journalist — a factory machine","A pilot — a restaurant stage"],answer:0,explanation:"يعمل flight attendant على الطائرة.",detail:"Mechanic يصلح الآلات، journalist يعمل في الأخبار، وpilot يقود الطائرة."},
  {id:"wm-v06",exam:"word-mastery",unit:3,skill:"vocabulary",prompt:"The manager asked the journalist to report the latest news. What does “report” mean here?",choices:["Give information about an event","Repair a broken machine","Design a new outfit","Measure a room"],answer:0,explanation:"Report هنا فعل يعني ينقل أو يقدم معلومات عن حدث.",detail:"الكلمة تتغير دلالتها حسب السياق؛ journalist وnews يحددان المعنى الإعلامي."},
  {id:"wm-v07",exam:"word-mastery",unit:4,skill:"vocabulary",prompt:"Before baking, Layla put flour, butter, and sugar on the countertop. These items are the ___.",choices:["ingredients","measurements","toppings only","dairy products"],answer:0,explanation:"Ingredients هي المكونات المستخدمة لصنع الطعام.",detail:"Topping يوضع فوق الطعام، أما ingredients فتشمل جميع مكونات الوصفة."},
  {id:"wm-v08",exam:"word-mastery",unit:4,skill:"vocabulary",prompt:"The cook poured the sauce slowly. Which action best describes “poured”?",choices:["Made liquid flow from a container","Moved food around with a spoon","Cut food into small pieces","Cooked food inside an oven"],answer:0,explanation:"Pour يعني يسكب سائلًا من وعاء.",detail:"Stir = يحرّك، cut = يقطع، bake = يخبز."},
  {id:"wm-v09",exam:"word-mastery",unit:5,skill:"vocabulary",prompt:"The final scene solved the mystery and showed what happened to every character. It was the story’s ___.",choices:["resolution","storyboard","rising tension","first act"],answer:0,explanation:"Resolution هي مرحلة حل الأحداث بعد الذروة.",detail:"Storyboard مخطط للمشاهد، وrising tension هو تصاعد التوتر قبل climax."},
  {id:"wm-v10",exam:"word-mastery",unit:5,skill:"vocabulary",prompt:"The actor spoke so quietly that only the person beside him could hear. He ___.",choices:["whispered","appeared","decided","argued"],answer:0,explanation:"Whisper تعني يتحدث بصوت منخفض جدًا.",detail:"Argue يعني يجادل، appear يعني يظهر، decide يعني يقرر."},
  {id:"wm-v11",exam:"word-mastery",unit:6,skill:"vocabulary",prompt:"Which item is essential for safety while rafting?",choices:["A life jacket","A fishing rod","A sleeping bag","Hiking boots"],answer:0,explanation:"Life jacket سترة نجاة ضرورية للسلامة في الأنشطة المائية.",detail:"السؤال لا يسأل عن أي غرض للرحلة، بل عن غرض safety while rafting."},
  {id:"wm-v12",exam:"word-mastery",unit:6,skill:"vocabulary",prompt:"A backpacker needs to see the path after sunset. Which item is most useful?",choices:["A flashlight","A surfboard","A campfire meal","A fishing rod"],answer:0,explanation:"Flashlight هو المصباح اليدوي المستخدم للرؤية في الظلام.",detail:"After sunset قرينة تدل على الحاجة إلى الضوء."},
  {id:"wm-v13",exam:"word-mastery",unit:7,skill:"vocabulary",prompt:"Passengers must show their passports before they pass through ___.",choices:["security","traffic","the railroad","the platform"],answer:0,explanation:"Security هو التفتيش الأمني في المطار.",detail:"Platform يرتبط بالقطار، وtraffic بحركة المركبات."},
  {id:"wm-v14",exam:"word-mastery",unit:7,skill:"vocabulary",prompt:"The plane is scheduled to depart at 9:00. What does “depart” mean?",choices:["Leave","Land","Check in","Find out"],answer:0,explanation:"Depart تعني يغادر.",detail:"Land تعني يهبط، وهي ليست عكس depart دائمًا في كل سياق لكنها هنا مشتت قريب."},
  {id:"wm-v15",exam:"word-mastery",unit:8,skill:"vocabulary",prompt:"Which description is logically correct?",choices:["A wool scarf can keep your neck warm.","A silver belt is always made of cotton.","A wooden necklace is made of silk.","A striped shirt has only round spots."],answer:0,explanation:"الصوف مادة دافئة ويمكن صنع وشاح منه.",detail:"Striped تعني مخططًا، بينما spotted تعني منقطًا."},
  {id:"wm-v16",exam:"word-mastery",unit:8,skill:"vocabulary",prompt:"The bracelet was handmade from a shiny gray metal. It was probably made of ___.",choices:["silver","cotton","leather","wool"],answer:0,explanation:"Silver فضة، وهي معدن رمادي لامع.",detail:"Cotton وwool ألياف، وleather جلد وليست معدنًا."},

  {id:"wm-w01",exam:"word-mastery",unit:1,skill:"writing",prompt:"Choose the only grammatically correct sentence.",choices:["My cousin enjoys making unusual paper models.","My cousin enjoy to make unusual paper models.","My cousin is enjoy making paper unusual models.","My cousin enjoyed make models unusually paper."],answer:0,explanation:"بعد enjoys نستخدم verb-ing، وترتيب الصفة قبل الاسم: unusual paper models.",detail:"Subject + enjoys + gerund + adjective + noun."},
  {id:"wm-w02",exam:"word-mastery",unit:2,skill:"writing",prompt:"Arrange the idea correctly: next year / will / an architect / redesign / our school",choices:["An architect will redesign our school next year.","Next year an architect redesign will our school.","Our school will an architect redesign next year.","An architect will next year our school redesigned."],answer:0,explanation:"الترتيب الصحيح: فاعل + will + فعل أساسي + مفعول + زمن.",detail:"بعد will نستخدم redesign دون s أو ed."},
  {id:"wm-w03",exam:"word-mastery",unit:2,skill:"writing",prompt:"Which sentence correctly expresses a planned action?",choices:["We are going to change the bedroom layout.","We will going to change the bedroom layout.","We are going change the layout bedroom.","We going to are change the bedroom’s layout."],answer:0,explanation:"الخطة المسبقة تصاغ بـ be going to + base verb.",detail:"Bedroom تصف layout، لذلك يأتي التركيب bedroom layout."},
  {id:"wm-w04",exam:"word-mastery",unit:3,skill:"writing",prompt:"Choose the correct sentence with a question tag.",choices:["The photographer works in this gallery, doesn’t she?","The photographer works in this gallery, isn’t she?","The photographer work in this gallery, doesn’t she?","The photographer works in this gallery, didn’t she?"],answer:0,explanation:"الفعل في المضارع البسيط works، لذلك نستخدم doesn’t في السؤال المذيل.",detail:"نختار الأداة من الفعل، لا من المهنة: works → does → doesn’t she?"},
  {id:"wm-w05",exam:"word-mastery",unit:3,skill:"writing",prompt:"Which sentence correctly shows an uncertain future possibility?",choices:["He might become an engineer because he enjoys designing things.","He might becomes an engineer because he enjoy designing.","He is might become engineer because he enjoys design.","He might to become an engineer because enjoys he designing."],answer:0,explanation:"بعد might نستخدم الفعل الأساسي become، وبعد enjoy نستخدم designing.",detail:"Might + base verb، وhe enjoys بإضافة s."},
  {id:"wm-w06",exam:"word-mastery",unit:4,skill:"writing",prompt:"Choose the clearest and correct cooking instruction.",choices:["If the dough is too dry, add a little water and mix it well.","If the dough too dry, adding a few water and mix it good.","If the dough was dry, add a little waters and mixed it.","The dough is too dry if add water a little and mixing well."],answer:0,explanation:"في التعليمات نستخدم if + present simple ثم فعل الأمر.",detail:"Water اسم غير معدود، لذلك نقول a little water لا a few waters."},
  {id:"wm-w07",exam:"word-mastery",unit:4,skill:"writing",prompt:"Which warning is formed correctly?",choices:["You had better not leave the cookies in the oven too long.","You had not better leaving the cookies in oven too long.","You better had not leave cookies too long in the oven.","You had better not left the cookies in the oven."],answer:0,explanation:"الصيغة الصحيحة: had better not + base verb.",detail:"بعد had better not يأتي leave بصورته الأساسية."},
  {id:"wm-w08",exam:"word-mastery",unit:5,skill:"writing",prompt:"Choose the sentence that correctly combines two actions in progress.",choices:["While Sara was drawing the storyboard, Ali was writing the plot.","While Sara drew the storyboard, Ali writing was the plot.","Sara was draw the storyboard while Ali was wrote the plot.","While was Sara drawing, Ali the plot was writing."],answer:0,explanation:"حدثان مستمران في الماضي: was drawing وwas writing.",detail:"While + subject + was/were + verb-ing."},
  {id:"wm-w09",exam:"word-mastery",unit:5,skill:"writing",prompt:"Which suggestion is correct and natural?",choices:["Why don’t we change the ending and add a new character?","Why don’t we changing the ending and adding a character?","How about change the ending and add a character?","What about we to change the ending and adding character?"],answer:0,explanation:"بعد Why don’t we نستخدم الفعل الأساسي: change وadd.",detail:"مع How about يمكن القول: How about changing the ending?"},
  {id:"wm-w10",exam:"word-mastery",unit:6,skill:"writing",prompt:"Choose the sentence with the correct use of when.",choices:["We were putting up the tent when the flashlight stopped working.","We put up the tent when the flashlight was stop working.","We were put up the tent when stopped the flashlight working.","When we were putting the tent up, the flashlight was stopped work."],answer:0,explanation:"حدث مستمر قطعه حدث قصير: were putting up / stopped.",detail:"Past progressive + when + simple past."},
  {id:"wm-w11",exam:"word-mastery",unit:6,skill:"writing",prompt:"Which sentence gives complete and correct safety advice?",choices:["You should wear a life jacket while you are canoeing.","You should wearing a life jacket while canoe.","You should to wear life jacket while you canoeing.","While you are canoeing should wear you a life jacket."],answer:0,explanation:"بعد should نستخدم wear، وبعد while نحتاج جملة سليمة.",detail:"Should + base verb. ويمكن أيضًا قول while canoeing اختصارًا."},
  {id:"wm-w12",exam:"word-mastery",unit:7,skill:"writing",prompt:"Choose the correct present perfect sentence.",choices:["The passengers have already checked in, but the plane hasn’t departed yet.","The passengers has already check in, but the plane didn’t departed yet.","The passengers have checked already in, but the plane hasn’t depart yet.","Already the passengers checking in, but yet the plane has not departed."],answer:0,explanation:"الجمع يأخذ have، والتصريفان الصحيحان checked وdeparted.",detail:"Already تأتي غالبًا بين have والتصريف الثالث، وyet في نهاية النفي."},
  {id:"wm-w13",exam:"word-mastery",unit:7,skill:"writing",prompt:"Which sentence uses the travel words in the correct order?",choices:["After we checked in, we went through security and walked to the gate.","After we went the gate, we checked security through and in.","We through security went after checked in to the gate.","After checking the gate, security went through our passports."],answer:0,explanation:"تسلسل السفر المنطقي واللغوي: check in ثم go through security ثم go to the gate.",detail:"Check in فعل مركب، وgo through security تعبير ثابت."},
  {id:"wm-w14",exam:"word-mastery",unit:8,skill:"writing",prompt:"Choose the correct question and short answer.",choices:["Have you tried the wool jacket? Yes, I have.","Did you have tried the wool jacket? Yes, I did tried.","Has you tried the wool jacket? Yes, I has.","Have you try the wool jacket? Yes, I tried have."],answer:0,explanation:"سؤال المضارع التام: Have + you + past participle، والإجابة Yes, I have.",detail:"التصريف الثالث من try هو tried."},
  {id:"wm-w15",exam:"word-mastery",unit:8,skill:"writing",prompt:"Which sentence correctly describes materials and patterns?",choices:["The striped belt is made of leather, and the spotted purse is made of cotton.","The striped belt made of leather, and the purse spotted is cotton made.","The belt is made from striped, and leather is the purse of cotton.","The leather belt is make of stripes and the cotton purse spotted."],answer:0,explanation:"الصفة قبل الاسم، والتركيب الصحيح is made of + material.",detail:"Striped belt وspotted purse، ثم leather وcotton للخامات."},
  {id:"wm-w16",exam:"word-mastery",unit:1,skill:"writing",prompt:"Choose the best sentence using both a state verb and an action verb.",choices:["I prefer documentaries, but I am watching a comedy right now.","I am preferring documentaries, but I watch a comedy right now.","I prefer documentaries, but I watching a comedy now.","I am prefer documentaries, but I am watch a comedy."],answer:0,explanation:"Prefer فعل حالة يأتي غالبًا بالمضارع البسيط، وwatching فعل جارٍ الآن.",detail:"State verb: prefer. Action happening now: am watching."},

  // أسئلة مصورة تحاكي نمط المطابقة والمفردات في النماذج المرفقة.
  {id:"pic-u1-1",unit:1,skill:"vocabulary",image:"assets/images/unit-1-picture-board.png",imageAlt:"Four numbered hobby pictures",prompt:"Which picture shows someone making origami?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:0,explanation:"الصورة 1 تعرض طفلًا يصنع شكلًا من الورق، وهذا هو origami.",detail:"Origami هو فن طي الورق لصنع أشكال مختلفة."},
  {id:"pic-u1-2",unit:1,skill:"reading",image:"assets/images/unit-1-picture-board.png",imageAlt:"Four numbered hobby pictures",prompt:"Which sentence matches Picture 2?",choices:["She is painting a landscape.","She is reading comic books.","She is riding a roller coaster.","She is making a paper model."],answer:1,explanation:"الصورة 2 تعرض طالبة تقرأ كتابًا مصورًا.",detail:"Reading comic books من الهوايات المذكورة في موضوع Personal Interests."},
  {id:"pic-u1-3",unit:1,skill:"general",image:"assets/images/unit-1-picture-board.png",imageAlt:"Four numbered hobby pictures",prompt:"What is the child in Picture 4 doing?",choices:["Painting","Reading","Riding","Making origami"],answer:0,explanation:"الصورة 4 تعرض طفلًا يحمل فرشاة ويرسم لوحة.",detail:"الصيغة الكاملة: The child is painting a picture."},

  {id:"pic-u2-1",unit:2,skill:"vocabulary",image:"assets/images/unit-2-picture-board.png",imageAlt:"Four numbered house and design pictures",prompt:"Which picture shows a fridge?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:0,explanation:"الصورة 1 تعرض ثلاجة ذات بابين.",detail:"A fridge keeps food and drinks cold."},
  {id:"pic-u2-2",unit:2,skill:"reading",image:"assets/images/unit-2-picture-board.png",imageAlt:"Four numbered house and design pictures",prompt:"Which sentence matches Picture 3?",choices:["The architect is checking the room’s measurements.","The family is cleaning the basement.","The cook is opening the fridge.","The carpenter is moving a shelf."],answer:0,explanation:"الصورة 3 تعرض شخصًا يقيس الغرفة قبل إعداد التصميم.",detail:"Architect وmeasurements من مفردات تصميم المنزل."},
  {id:"pic-u2-3",unit:2,skill:"vocabulary",image:"assets/images/unit-2-picture-board.png",imageAlt:"Four numbered house and design pictures",prompt:"Picture 4 shows the part of a house below ground. It is the ___.",choices:["entrance","shelf","basement","layout"],answer:2,explanation:"الجزء الموجود أسفل المنزل يسمى basement.",detail:"Basement طابق أو غرفة تقع تحت مستوى الأرض."},

  {id:"pic-u3-1",unit:3,skill:"vocabulary",image:"assets/images/unit-3-picture-board.png",imageAlt:"Four numbered job pictures",prompt:"Which picture shows a mechanic?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:0,explanation:"الصورة 1 تعرض شخصًا يصلح سيارة ويحمل أداة.",detail:"A mechanic repairs cars and machines."},
  {id:"pic-u3-2",unit:3,skill:"reading",image:"assets/images/unit-3-picture-board.png",imageAlt:"Four numbered job pictures",prompt:"Which sentence matches Picture 3?",choices:["She takes professional photographs.","She helps passengers on an airplane.","She repairs cars in a garage.","She flies the airplane."],answer:1,explanation:"الصورة 3 تعرض مضيفة طيران داخل الطائرة.",detail:"A flight attendant helps passengers during a flight."},
  {id:"pic-u3-3",unit:3,skill:"vocabulary",image:"assets/images/unit-3-picture-board.png",imageAlt:"Four numbered job pictures",prompt:"The person in Picture 2 uses a camera at work. She is a ___.",choices:["pilot","manager","photographer","mechanic"],answer:2,explanation:"الشخص الذي يلتقط الصور باحتراف هو photographer.",detail:"اربط camera بالمهنة photographer."},

  {id:"pic-u4-1",unit:4,skill:"vocabulary",image:"assets/images/unit-4-picture-board.png",imageAlt:"Four numbered food and cooking pictures",prompt:"Which picture shows someone stirring food?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:1,explanation:"الصورة 2 تعرض ملعقة تحرك الطعام داخل القدر.",detail:"Stir تعني تحريك الطعام أو السائل، غالبًا بحركة دائرية."},
  {id:"pic-u4-2",unit:4,skill:"reading",image:"assets/images/unit-4-picture-board.png",imageAlt:"Four numbered food and cooking pictures",prompt:"Which sentence matches Picture 1?",choices:["The yogurt has fruit and a little honey on top.","The soup is baking in the oven.","The ingredients are on the countertop.","The cook is stirring the soup."],answer:0,explanation:"الصورة 1 تعرض وعاء زبادي وفاكهة وعسلًا في الأعلى.",detail:"On top تشير إلى الشيء الموضوع فوق الطعام."},
  {id:"pic-u4-3",unit:4,skill:"general",image:"assets/images/unit-4-picture-board.png",imageAlt:"Four numbered food and cooking pictures",prompt:"Before cooking, the items in Picture 3 are called ___.",choices:["directions","ingredients","measurements","characters"],answer:1,explanation:"المواد المستخدمة في إعداد الوصفة تسمى ingredients.",detail:"Flour, eggs, butter, and sugar are ingredients."},

  {id:"pic-u5-1",unit:5,skill:"vocabulary",image:"assets/images/unit-5-picture-board.png",imageAlt:"Four numbered story genre and storyboard pictures",prompt:"Which picture represents a western?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:2,explanation:"الصورة 3 تعرض راعي بقر بقبعة، وهو رمز لنوع western.",detail:"Western stories often include cowboys and life in the old American West."},
  {id:"pic-u5-2",unit:5,skill:"vocabulary",image:"assets/images/unit-5-picture-board.png",imageAlt:"Four numbered story genre and storyboard pictures",prompt:"Picture 4 is used to plan the scenes of a story. It is a ___.",choices:["character","storyboard","comedy","resolution"],answer:1,explanation:"المربعات المتتابعة التي تخطط للمشاهد تسمى storyboard.",detail:"A storyboard shows the planned order of scenes before filming or writing."},
  {id:"pic-u5-3",unit:5,skill:"reading",image:"assets/images/unit-5-picture-board.png",imageAlt:"Four numbered story genre and storyboard pictures",prompt:"Which sentence matches Picture 2?",choices:["The story is a comedy that makes everyone laugh.","The story is a horror story with a frightening ghost.","The story is a western about a cowboy.","The students are drawing a storyboard."],answer:1,explanation:"الصورة 2 تعرض شبحًا مخيفًا، لذلك تمثل horror.",detail:"Horror stories are designed to frighten the audience."},

  {id:"pic-u6-1",unit:6,skill:"vocabulary",image:"assets/images/unit-6-picture-board.png",imageAlt:"Four numbered outdoor activity and equipment pictures",prompt:"Which picture shows rafting?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:0,explanation:"الصورة 1 تعرض أشخاصًا في قارب مطاطي يستخدمون المجاديف.",detail:"Rafting نشاط مائي يحتاج إلى life jacket للسلامة."},
  {id:"pic-u6-2",unit:6,skill:"reading",image:"assets/images/unit-6-picture-board.png",imageAlt:"Four numbered outdoor activity and equipment pictures",prompt:"Which sentence matches Picture 2?",choices:["They are putting up a tent beside a campfire.","They are carrying a sleeping bag on the train.","They are wearing a helmet in the kitchen.","They are rafting down a river."],answer:0,explanation:"الصورة 2 تعرض خيمة ونار مخيم.",detail:"Putting up a tent and making a campfire are camping activities."},
  {id:"pic-u6-3",unit:6,skill:"general",image:"assets/images/unit-6-picture-board.png",imageAlt:"Four numbered outdoor activity and equipment pictures",prompt:"Which item protects your head while climbing?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:2,explanation:"الصورة 3 تعرض خوذة climbing helmet لحماية الرأس.",detail:"Wear a helmet when climbing to reduce the risk of head injuries."},

  {id:"pic-u7-1",unit:7,skill:"vocabulary",image:"assets/images/unit-7-picture-board.png",imageAlt:"Four numbered travel pictures",prompt:"Which picture shows passengers waiting on a platform?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:1,explanation:"الصورة 2 تعرض مسافرًا ينتظر بجانب رصيف المحطة.",detail:"Passengers wait for trains on a platform."},
  {id:"pic-u7-2",unit:7,skill:"reading",image:"assets/images/unit-7-picture-board.png",imageAlt:"Four numbered travel pictures",prompt:"Which sentence matches Picture 1?",choices:["The passenger is going through airport security.","The passenger is waiting for a taxi.","The passenger has packed a suitcase.","The passenger has arrived at the platform."],answer:0,explanation:"الصورة 1 تعرض بوابة التفتيش الأمني في المطار.",detail:"Travelers go through security before walking to the gate."},
  {id:"pic-u7-3",unit:7,skill:"spelling",image:"assets/images/unit-7-picture-board.png",imageAlt:"Four numbered travel pictures",prompt:"Complete the word for Picture 3: sui_case",choices:["t","p","b","x"],answer:0,explanation:"الكلمة الصحيحة suitcase، والحرف الناقص t.",detail:"Suitcase حقيبة سفر، وتهجئتها suit + case."},

  {id:"pic-u8-1",unit:8,skill:"vocabulary",image:"assets/images/unit-8-picture-board.png",imageAlt:"Four numbered clothes and accessory pictures",prompt:"Which picture shows an accessory worn around the neck?",choices:["Picture 1","Picture 2","Picture 3","Picture 4"],answer:1,explanation:"الصورة 2 تعرض necklace، وهي قلادة تلبس حول الرقبة.",detail:"A bracelet is worn around the wrist, while a necklace is worn around the neck."},
  {id:"pic-u8-2",unit:8,skill:"reading",image:"assets/images/unit-8-picture-board.png",imageAlt:"Four numbered clothes and accessory pictures",prompt:"Which sentence matches Picture 3?",choices:["The shirt is striped.","The scarf is spotted.","The belt is made of silver.","The necklace is made of wool."],answer:0,explanation:"الصورة 3 تعرض قميصًا بخطوط، أي striped shirt.",detail:"Striped يعني مخططًا، وspotted يعني منقطًا."},
  {id:"pic-u8-3",unit:8,skill:"vocabulary",image:"assets/images/unit-8-picture-board.png",imageAlt:"Four numbered clothes and accessory pictures",prompt:"Picture 1 is warm and comes from sheep. It is made of ___.",choices:["metal","plastic","wool","silver"],answer:2,explanation:"الوشاح في الصورة مصنوع من wool، وهو الصوف الذي يأتي من الأغنام.",detail:"Wool is a warm natural material used for scarves and sweaters."},

  // أسئلة مصورة أصعب ضمن اختبار إتقان الكلمات والجمل.
  {id:"wm-pic-u1",exam:"word-mastery",unit:1,skill:"writing",image:"assets/images/unit-1-picture-board.png",imageAlt:"Four numbered hobby pictures",prompt:"Which sentence correctly contrasts Picture 1 with Picture 4?",choices:["The child in Picture 1 is making origami, while the child in Picture 4 is painting.","The child in Picture 1 paints, while Picture 4 is make origami.","Picture 1 is making a ride, but the child in Picture 4 reading.","The children both enjoys to make paper models."],answer:0,explanation:"الجملة الأولى تصف الصورتين بقواعد وترتيب صحيحين.",detail:"نستخدم is making وis painting لوصف فعلين يجريان في الصور."},
  {id:"wm-pic-u2",exam:"word-mastery",unit:2,skill:"vocabulary",image:"assets/images/unit-2-picture-board.png",imageAlt:"Four numbered house and design pictures",prompt:"The professional in Picture 3 needs exact sizes before changing the layout. Which word names those sizes?",choices:["Measurements","Furniture","Entrances","Cushions"],answer:0,explanation:"الأحجام والأبعاد الدقيقة تسمى measurements.",detail:"السياق البصري للقياس وكلمة exact sizes يحددان الإجابة."},
  {id:"wm-pic-u3",exam:"word-mastery",unit:3,skill:"writing",image:"assets/images/unit-3-picture-board.png",imageAlt:"Four numbered job pictures",prompt:"Choose the only sentence that correctly compares Pictures 2 and 4.",choices:["The photographer takes pictures, whereas the pilot flies an airplane.","The photographer fly an airplane, whereas the pilot take pictures.","A photographer is taking flights and a pilot photographs cameras.","The pilot might flies while the photographer might takes photos."],answer:0,explanation:"الصورة 2 photographer والصورة 4 pilot، والجملة الأولى تستخدم الأفعال الصحيحة.",detail:"مع المفرد في المضارع البسيط: takes وflies."},
  {id:"wm-pic-u4",exam:"word-mastery",unit:4,skill:"vocabulary",image:"assets/images/unit-4-picture-board.png",imageAlt:"Four numbered food and cooking pictures",prompt:"Which pair correctly names the action in Picture 2 and the items in Picture 3?",choices:["stir — ingredients","pour — measurements","bake — characters","fetch — directions"],answer:0,explanation:"في الصورة 2 يتم stir للطعام، والصورة 3 تعرض ingredients.",detail:"السؤال يختبر التمييز بين فعل الطبخ واسم مكونات الوصفة."},
  {id:"wm-pic-u5",exam:"word-mastery",unit:5,skill:"writing",image:"assets/images/unit-5-picture-board.png",imageAlt:"Four numbered story genre and storyboard pictures",prompt:"Which suggestion correctly uses the planning tool in Picture 4?",choices:["How about drawing a storyboard before we write the final scene?","How about draw a storyboard before writing we the scene?","Why don’t drawing the storyboard before to write?","What about we draws a storyboard for wrote the scene?"],answer:0,explanation:"بعد How about نستخدم verb-ing: drawing، والجملة مرتبة بشكل صحيح.",detail:"Picture 4 is a storyboard, which helps organize scenes."},
  {id:"wm-pic-u6",exam:"word-mastery",unit:6,skill:"vocabulary",image:"assets/images/unit-6-picture-board.png",imageAlt:"Four numbered outdoor activity and equipment pictures",prompt:"A student selects Pictures 3 and 4 for a packing list. Which description is most accurate?",choices:["Protective headgear and equipment for sleeping","Two different water sports","Cooking tools for a campfire","Transport items for a train journey"],answer:0,explanation:"الصورة 3 خوذة للحماية والصورة 4 حقيبة نوم.",detail:"Headgear تعني ما يلبس لحماية الرأس، وsleeping equipment تشمل sleeping bag."},
  {id:"wm-pic-u7",exam:"word-mastery",unit:7,skill:"writing",image:"assets/images/unit-7-picture-board.png",imageAlt:"Four numbered travel pictures",prompt:"Which sentence gives the most logical travel sequence using Pictures 1 and 2?",choices:["After we went through security, we traveled to the station and waited on the platform.","We waited in the suitcase before security reached the platform.","After the platform checked in, security packed our taxi.","We have went security and then the platform has wait."],answer:0,explanation:"الجملة الأولى تستخدم security وplatform في سياق وتسلسل منطقيين.",detail:"Go through security تعبير ثابت، وwait on the platform تعبير صحيح."},
  {id:"wm-pic-u8",exam:"word-mastery",unit:8,skill:"vocabulary",image:"assets/images/unit-8-picture-board.png",imageAlt:"Four numbered clothes and accessory pictures",prompt:"Which description correctly identifies both pattern and material clues in the board?",choices:["Picture 3 is striped, and the warm item in Picture 1 can be made of wool.","Picture 3 is spotted, and Picture 1 must be made of metal.","Picture 2 is a leather belt, and Picture 4 is a silver necklace.","Picture 1 is plastic jewelry, and Picture 3 is a wool bracelet."],answer:0,explanation:"القميص في الصورة 3 مخطط، والوشاح الدافئ في الصورة 1 يمكن أن يكون من الصوف.",detail:"فرّق بين pattern مثل striped وبين material مثل wool."}
];
